fn main() {
    // Without this, cargo runs the build script again after any change in the
    // package. (The `regen-openapi` feature adds the schema file.)
    println!("cargo:rerun-if-changed=build.rs");

    #[cfg(feature = "regen-openapi")]
    regen_openapi::run();

    #[cfg(feature = "python-stubgen")]
    stub_gen_rpath();
}

/// Adds the library directory of the Python that pyo3 builds for to the
/// rpath of the `stub_gen` binary only. `stub_gen` embeds Python, so it is
/// linked to a libpython, and a uv-managed Python keeps that library in a
/// directory that the dynamic loader does not search. Without this, running
/// `target/debug/stub_gen` fails with "libpython3.x.so.1.0: cannot open
/// shared object file".
///
/// pyo3 does this itself for its own binaries and tests, but a link argument
/// from a dependency's build script does not reach this crate's binaries.
/// Linux only: other platforms do not use `lib_dir` in the same way.
#[cfg(feature = "python-stubgen")]
fn stub_gen_rpath() {
    println!("cargo:rerun-if-env-changed=PYO3_PYTHON");
    if let Some(lib_dir) = pyo3_build_config::get().lib_dir() {
        println!("cargo:rustc-link-arg-bin=stub_gen=-Wl,-rpath,{lib_dir}");
    }
}

/// Regenerates src/mwa_asvo/api/openapi.rs from the MWA ASVO v2 OpenAPI
/// schema, using typify (https://github.com/oxidecomputer/typify).
///
/// Only compiled in behind the `regen-openapi` feature (off by default),
/// so a normal build doesn't need typify, schemars, syn, or prettyplease
/// at all. Enable it when preparing a release after the schema has
/// changed:
///
///     cargo build --features regen-openapi
///     git diff src/mwa_asvo/api/openapi.rs
///
/// See tools/generate_openapi.sh for how openapi-schema.json itself gets
/// updated from the real server - that part is a separate, manual,
/// network-touching step, deliberately kept out of the build.
#[cfg(feature = "regen-openapi")]
mod regen_openapi {
    use std::fs;
    use std::path::Path;

    use schemars::schema::{InstanceType, SchemaObject};
    use typify::{TypeSpace, TypeSpaceImpl, TypeSpacePatch, TypeSpaceSettings};

    const SCHEMA_PATH: &str = "src/mwa_asvo/api/openapi-schema.json";
    const OUTPUT_PATH: &str = "src/mwa_asvo/api/openapi.rs";
    /// The Rust type for a schema `date-time` string. typify's own choice
    /// is `chrono::DateTime<Utc>`; giant-squid uses jiff instead (chrono is
    /// soft-deprecated). Every MWA ASVO time is UTC, so a `Timestamp` fits.
    const DATE_TIME_TYPE: &str = "::jiff::Timestamp";
    /// The JSON Schema format that `DATE_TIME_TYPE` replaces.
    const DATE_TIME_FORMAT: &str = "date-time";
    /// The derive added to every generated type.
    const ALL_TYPES_DERIVE: &str = "PartialEq";
    /// The schema's job type code, and the derives it gets as well.
    const JOB_TYPE: &str = "JobType";
    const JOB_TYPE_DERIVES: [&str; 3] = ["Copy", "Eq", "Hash"];

    // No embedded generation timestamp on purpose: build.rs runs on every
    // build, so a timestamp here would make the file "change" (and the CI
    // drift-check fail) even when the schema hasn't, which would defeat
    // the point of that check.
    const HEADER: &str = "\
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

//
// The code in this file is AUTOGENERATED by build.rs (with
// --features regen-openapi), from src/mwa_asvo/api/openapi-schema.json.
// Manual edits or modifications will be lost next time it is generated!
//
";

    pub fn run() {
        // Only rerun this build script when the schema itself changes -
        // without this, cargo's default is to rerun on ANY file change in
        // the package, which would include the very openapi.rs file we
        // write below, causing needless reruns (though not an infinite
        // loop - cargo doesn't treat writes during a build as new changes
        // for that same build).
        println!("cargo:rerun-if-changed={SCHEMA_PATH}");

        let content = fs::read_to_string(SCHEMA_PATH)
            .unwrap_or_else(|e| panic!("failed to read {SCHEMA_PATH}: {e}"));
        let schema: schemars::schema::RootSchema = serde_json::from_str(&content)
            .unwrap_or_else(|e| panic!("failed to parse {SCHEMA_PATH} as a JSON schema: {e}"));

        // typify matches a conversion on the schema without its metadata
        // (title, description), so this one entry covers every `date-time`
        // field, including the optional ones (inside `anyOf`).
        let date_time = SchemaObject {
            instance_type: Some(InstanceType::String.into()),
            format: Some(DATE_TIME_FORMAT.to_string()),
            ..Default::default()
        };
        // `JobType` is an integer code: it compares, hashes and copies as
        // one, so the library can filter and match on it.
        let mut job_type_patch = TypeSpacePatch::default();
        for derive in JOB_TYPE_DERIVES {
            job_type_patch.with_derive(derive);
        }
        let mut settings = TypeSpaceSettings::default();
        settings
            .with_struct_builder(true)
            .with_conversion(
                date_time,
                DATE_TIME_TYPE,
                [TypeSpaceImpl::Display, TypeSpaceImpl::FromStr].into_iter(),
            )
            // Every type compares, so a program (and the tests) can compare
            // jobs, files and request bodies.
            .with_derive(ALL_TYPES_DERIVE.to_string())
            .with_patch(JOB_TYPE, &job_type_patch);
        let mut type_space = TypeSpace::new(&settings);
        type_space
            .add_root_schema(schema)
            .expect("typify failed to process the openapi schema");

        let generated = prettyplease::unparse(
            &syn::parse2::<syn::File>(type_space.to_stream())
                .expect("typify produced tokens that aren't a valid Rust file"),
        );

        fs::write(Path::new(OUTPUT_PATH), format!("{HEADER}{generated}"))
            .unwrap_or_else(|e| panic!("failed to write {OUTPUT_PATH}: {e}"));

        println!(
            "cargo:warning=Regenerated {OUTPUT_PATH} from {SCHEMA_PATH} - review and commit it."
        );
    }
}
