fn main() {
    // Gather build time info
    built::write_built_file().expect("Failed to acquire build-time information");

    #[cfg(feature = "regen-openapi")]
    regen_openapi::run();
}

/// Regenerates src/asvo/apiv2/openapi.rs from the MWA ASVO v2 OpenAPI
/// schema, using typify (https://github.com/oxidecomputer/typify).
///
/// Only compiled in behind the `regen-openapi` feature (off by default),
/// so a normal build doesn't need typify, schemars, syn, or prettyplease
/// at all. Enable it when preparing a release after the schema has
/// changed:
///
///     cargo build --features regen-openapi
///     git diff src/asvo/apiv2/openapi.rs
///
/// See tools/generate_openapi.sh for how openapi-schema.json itself gets
/// updated from the real server - that part is a separate, manual,
/// network-touching step, deliberately kept out of the build.
#[cfg(feature = "regen-openapi")]
mod regen_openapi {
    use std::fs;
    use std::path::Path;

    use schemars::schema::{InstanceType, SchemaObject};
    use typify::{TypeSpace, TypeSpaceImpl, TypeSpaceSettings};

    const SCHEMA_PATH: &str = "src/asvo/apiv2/openapi-schema.json";
    const OUTPUT_PATH: &str = "src/asvo/apiv2/openapi.rs";
    /// The Rust type for a schema `date-time` string. typify's own choice
    /// is `chrono::DateTime<Utc>`; giant-squid uses jiff instead (chrono is
    /// soft-deprecated). Every MWA ASVO time is UTC, so a `Timestamp` fits.
    const DATE_TIME_TYPE: &str = "::jiff::Timestamp";
    /// The JSON Schema format that `DATE_TIME_TYPE` replaces.
    const DATE_TIME_FORMAT: &str = "date-time";

    // No embedded generation timestamp on purpose: build.rs runs on every
    // build, so a timestamp here would make the file "change" (and the CI
    // drift-check fail) even when the schema hasn't, which would defeat
    // the point of that check.
    const HEADER: &str = "\
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

//
// The code in this file is AUTOGENERATED by build.rs (with
// --features regen-openapi), from src/asvo/apiv2/openapi-schema.json.
// Manual edits or modifications will be lost next time it is generated!
//
";

    pub fn run() {
        // Only rerun this build script when the schema itself changes -
        // without this, cargo's default is to rerun on ANY file change in
        // the package, which would include the very openapi.rs file we
        // write below, causing needless reruns (though not an infinite
        // loop - cargo doesn't treat writes during a build as new changes
        // for that same build).
        println!("cargo:rerun-if-changed={SCHEMA_PATH}");

        let content = fs::read_to_string(SCHEMA_PATH)
            .unwrap_or_else(|e| panic!("failed to read {SCHEMA_PATH}: {e}"));
        let schema: schemars::schema::RootSchema = serde_json::from_str(&content)
            .unwrap_or_else(|e| panic!("failed to parse {SCHEMA_PATH} as a JSON schema: {e}"));

        // typify matches a conversion on the schema without its metadata
        // (title, description), so this one entry covers every `date-time`
        // field, including the optional ones (inside `anyOf`).
        let date_time = SchemaObject {
            instance_type: Some(InstanceType::String.into()),
            format: Some(DATE_TIME_FORMAT.to_string()),
            ..Default::default()
        };
        let mut type_space = TypeSpace::new(
            TypeSpaceSettings::default()
                .with_struct_builder(true)
                .with_conversion(
                    date_time,
                    DATE_TIME_TYPE,
                    [TypeSpaceImpl::Display, TypeSpaceImpl::FromStr].into_iter(),
                ),
        );
        type_space
            .add_root_schema(schema)
            .expect("typify failed to process the openapi schema");

        let generated = prettyplease::unparse(
            &syn::parse2::<syn::File>(type_space.to_stream())
                .expect("typify produced tokens that aren't a valid Rust file"),
        );

        fs::write(Path::new(OUTPUT_PATH), format!("{HEADER}{generated}"))
            .unwrap_or_else(|e| panic!("failed to write {OUTPUT_PATH}: {e}"));

        println!(
            "cargo:warning=Regenerated {OUTPUT_PATH} from {SCHEMA_PATH} - review and commit it."
        );
    }
}
