# This file is automatically generated by pyo3_stub_gen
r"""
Python bindings for giant-squid, a client for the MWA ASVO.
"""

import builtins
import collections.abc
import datetime
import enum
import os
import pathlib
import typing

__all__ = [
    "DEFAULT_CONCURRENT_DOWNLOADS",
    "ENDPOINT_BEAMFORMER_JOB",
    "ENDPOINT_CONVERSION_JOB",
    "ENDPOINT_DOWNLOAD_VIS_JOB",
    "ENDPOINT_IMAGE_FROM_JOB",
    "ENDPOINT_IMAGING_JOB",
    "ENDPOINT_JOBS",
    "ENDPOINT_VOLTAGE_JOB",
    "ENV_GIANT_SQUID_DELIVERY",
    "ENV_GIANT_SQUID_DELIVERY_FORMAT",
    "WAIT_INITIAL_DELAY_SECS",
    "WAIT_POLL_INTERVAL_SECS",
    "AsvoApiError",
    "AsvoClient",
    "AsvoError",
    "AsvoFilesArray",
    "AsvoJob",
    "AsvoJobProduct",
    "AsvoJobState",
    "AsvoJobType",
    "AsvoJobVec",
    "Centre",
    "Delivery",
    "DeliveryFormat",
    "DownloadProgress",
    "DownloadSettings",
    "JobSubmittedResponse",
    "Output",
    "OutputMode",
    "Polarization",
    "Weighting",
    "beamformer_job_params",
    "conversion_job_params",
    "download_meta_job_params",
    "download_vis_job_params",
    "image_from_job_params",
    "imaging_job_params",
    "parse_many_job_ids_or_obs_ids",
    "reset_logging",
    "voltage_job_params",
]

DEFAULT_CONCURRENT_DOWNLOADS: builtins.int
ENDPOINT_BEAMFORMER_JOB: builtins.str
ENDPOINT_CONVERSION_JOB: builtins.str
ENDPOINT_DOWNLOAD_VIS_JOB: builtins.str
ENDPOINT_IMAGE_FROM_JOB: builtins.str
ENDPOINT_IMAGING_JOB: builtins.str
ENDPOINT_JOBS: builtins.str
ENDPOINT_VOLTAGE_JOB: builtins.str
ENV_GIANT_SQUID_DELIVERY: builtins.str
ENV_GIANT_SQUID_DELIVERY_FORMAT: builtins.str
WAIT_INITIAL_DELAY_SECS: builtins.float
WAIT_POLL_INTERVAL_SECS: builtins.float
__version__: builtins.str

class AsvoApiError(builtins.Exception):
    r"""
    An MWA ASVO API call failed. `kind` is the Rust `AsvoApiError` variant.

    `kind` is always set. The other attributes are set only for the kinds shown.
    """

    kind: builtins.str
    r"""
    "MissingAuthKey", "AuthenticationFailed", "Conversion", "BadJson", "Reqwest", "ApiError" or "BadStatus".
    """
    message: builtins.str
    r"""
    AuthenticationFailed, ApiError and BadStatus.
    """
    error_code: builtins.str
    r"""
    ApiError: the server's machine-readable error code.
    """
    detail: builtins.str | None
    r"""
    ApiError.
    """
    suggestion: builtins.str | None
    r"""
    ApiError.
    """
    field_errors: builtins.list[builtins.dict[builtins.str, builtins.str]]
    r"""
    ApiError: the fields that failed validation, each as `{"field": ..., "message": ...}`. Can be empty.
    """
    request_id: builtins.str | None
    r"""
    ApiError: the server's ID for the request, for a support request.
    """
    code: builtins.int
    r"""
    BadStatus: the HTTP status code.
    """

@typing.final
class AsvoClient:
    r"""
    A client for the MWA ASVO. It logs in when it is created.

    Args:
        host: The MWA ASVO base URL, for example
            "https://asvo.mwatelescope.org:443". An "http://" host is
            permitted (a local test server); every other host must use TLS.
        api_key: Your MWA ASVO API key.
        api_timeout: The timeout for one API request, in seconds. `None`
            uses the library default (60 s).
        token_cache_path: Where to cache the session between runs. `None`
            keeps the session in memory only, so every new client logs in.
            Give a path for a script that runs often, because the server
            permits only a few logins a minute.

    Raises:
        AsvoApiError: The API key is empty, or the login failed.
        ValueError: `api_timeout` is negative or not finite.
    """
    def __new__(
        cls,
        host: builtins.str,
        api_key: builtins.str,
        *,
        api_timeout: builtins.float | None = None,
        token_cache_path: builtins.str | os.PathLike | pathlib.Path | None = None,
    ) -> AsvoClient: ...
    @staticmethod
    def from_env() -> AsvoClient:
        r"""
        Make a client from the environment variables of the `giant-squid`
        command, and log in.

        This is the one place where the module reads the environment, and it
        does so only when you call it. `MWA_ASVO_API_KEY` is required.
        `MWA_ASVO_HOST` is the host (default: the MWA ASVO), `MWA_ASVO_API_TIMEOUT`
        is the time limit of a request in whole seconds, and the session is
        cached in `$HOME/.mwa-asvo/tokens.json`, shared with the `giant-squid`
        command. A value of `MWA_ASVO_API_TIMEOUT` that is not a whole number
        of seconds is logged as a warning and the default is used.

        Raises:
            AsvoApiError: `MWA_ASVO_API_KEY` is not set, or the login failed.
        """
    def get_jobs(
        self,
        days: builtins.int | None = None,
        *,
        job_state: AsvoJobState | None = None,
        job_type: AsvoJobType | None = None,
        date_from: datetime.datetime | None = None,
        date_to: datetime.datetime | None = None,
        sort_by: builtins.str | None = None,
    ) -> AsvoJobVec:
        r"""
        Get your jobs. The server filters them; every filter that is `None`
        does not filter.

        Args:
            days: Only the jobs from the past `days` days, from 1 to 30.
                `None` is the default of the MWA ASVO API.
            job_state: Only the jobs in this state. The server takes one
                state; to filter by several, use `AsvoJobVec.filter`.
                `AsvoJobState.Expired` cannot be filtered by.
            job_type: Only the jobs of this type. `AsvoJobType.Unknown`
                cannot be filtered by.
            date_from: Only the jobs created at or after this time. It must
                have a time zone.
            date_to: Only the jobs created at or before this time. It must
                have a time zone.
            sort_by: The column to sort the jobs by, for example "id".
                `None` uses the server's default order.

        Raises:
            ValueError: `days` is not from 1 to 30, or `job_state` or
                `job_type` cannot be filtered by.
            TypeError: `date_from` or `date_to` has no time zone.
            AsvoApiError: The request failed.
        """
    def list_jobs(
        self,
        job_ids: typing.Sequence[builtins.int] | None = None,
        obs_ids: typing.Sequence[builtins.int] | None = None,
        job_types: typing.Sequence[AsvoJobType] | None = None,
        job_states: typing.Sequence[AsvoJobState] | None = None,
        *,
        days: builtins.int | None = None,
        date_from: datetime.datetime | None = None,
        date_to: datetime.datetime | None = None,
        sort_by: builtins.str | None = None,
    ) -> AsvoJobVec:
        r"""
        List jobs as `giant-squid list` does: the server filters what it
        can, and the lists (several job IDs, obsids, types or states) are
        applied to the result. Every filter that is `None` does not filter.

        Args:
            job_ids: Only these jobs. Cannot be combined with `obs_ids`.
            obs_ids: Only the jobs for these obsids.
            job_types: Only the jobs of these types.
            job_states: Only the jobs in these states. States compare by
                kind, so `AsvoJobState.Error` matches every job with an
                error. `AsvoJobState.Expired` works here too.
            days: Only the jobs from the past `days` days, from 1 to 30.
                `None` is the default of the MWA ASVO API.
            date_from: Only the jobs created at or after this time. It must
                have a time zone.
            date_to: Only the jobs created at or before this time. It must
                have a time zone.
            sort_by: The column to sort the jobs by, for example "id".

        Raises:
            ValueError: Both `job_ids` and `obs_ids` are given, an obsid is
                not valid, or `days` is not from 1 to 30.
            TypeError: `date_from` or `date_to` has no time zone.
            AsvoApiError: The request failed.
        """
    def submit_download_vis_job(
        self,
        obs_id: builtins.int,
        *,
        delivery: Delivery | None = None,
        delivery_format: DeliveryFormat | None = None,
        allow_resubmit: builtins.bool | None = None,
    ) -> JobSubmittedResponse:
        r"""
        Submit a job to download an observation's raw visibilities.

        Every keyword argument that is `None` uses the MWA ASVO's default.

        Args:
            obs_id: The obsid.
            delivery: Where the MWA ASVO delivers the data.
            delivery_format: How the MWA ASVO packages the files.
            allow_resubmit: Submit the job even if an identical one has
                completed.

        Returns:
            The server's reply, with the new job's ID.

        Raises:
            ValueError: `obs_id` is not a valid obsid.
            AsvoApiError: The request failed.
        """
    def submit_download_meta_job(
        self,
        obs_id: builtins.int,
        *,
        delivery: Delivery | None = None,
        delivery_format: DeliveryFormat | None = None,
        allow_resubmit: builtins.bool | None = None,
    ) -> JobSubmittedResponse:
        r"""
        Submit a job to download an observation's metadata.

        The arguments are those of `submit_download_vis_job`.

        Returns:
            The server's reply, with the new job's ID.

        Raises:
            ValueError: `obs_id` is not a valid obsid.
            AsvoApiError: The request failed.
        """
    def submit_conversion_job(
        self,
        obs_id: builtins.int,
        *,
        delivery: Delivery | None = None,
        delivery_format: DeliveryFormat | None = None,
        output: Output | None = None,
        avg_freq_res: builtins.float | None = None,
        avg_time_res: builtins.float | None = None,
        flag_edge_width: builtins.float | None = None,
        apply_di_cal: builtins.bool | None = None,
        centre: Centre | None = None,
        custom_centre_ra: builtins.float | None = None,
        custom_centre_dec: builtins.float | None = None,
        no_apply_amps: builtins.bool | None = None,
        no_digital_gains: builtins.bool | None = None,
        no_flag_dc: builtins.bool | None = None,
        no_geometry_delay: builtins.bool | None = None,
        no_passband_gains: builtins.bool | None = None,
        no_cable_delay: builtins.bool | None = None,
        no_rfi: builtins.bool | None = None,
        allow_resubmit: builtins.bool | None = None,
    ) -> JobSubmittedResponse:
        r"""
        Submit a conversion (preprocessing) job.

        Every keyword argument that is `None` uses the MWA ASVO's default.

        Args:
            obs_id: The obsid.
            delivery: Where the MWA ASVO delivers the data.
            delivery_format: How the MWA ASVO packages the files.
            output: The output format.
            avg_freq_res: The frequency resolution to average to (kHz).
            avg_time_res: The time resolution to average to (s).
            flag_edge_width: The width of the frequency edge flagging (kHz).
            apply_di_cal: Apply the DI calibration solution.
            centre: The phase centre mode. `Centre.Custom` needs
                `custom_centre_ra` and `custom_centre_dec`.
            custom_centre_ra: The custom phase centre's right ascension
                (degrees).
            custom_centre_dec: The custom phase centre's declination
                (degrees).
            no_apply_amps: Do not apply the amplitude calibration solutions.
            no_digital_gains: Do not apply the digital gains.
            no_flag_dc: Do not flag the DC channel.
            no_geometry_delay: Do not apply the geometric delay corrections.
            no_passband_gains: Do not apply the passband gain corrections.
            no_cable_delay: Do not apply the cable delay corrections.
            no_rfi: Do not flag RFI.
            allow_resubmit: Submit the job even if an identical one has
                completed.

        Returns:
            The server's reply, with the new job's ID.

        Raises:
            ValueError: `obs_id` is not a valid obsid, or a number is outside
                what the MWA ASVO accepts (for example `avg_freq_res` above
                1280). The message names the argument and its limits.
                Nothing is sent.
            AsvoApiError: The request failed.
        """
    def submit_imaging_job(
        self,
        obs_id: builtins.int,
        *,
        delivery: Delivery | None = None,
        delivery_format: DeliveryFormat | None = None,
        apply_di_cal: builtins.bool | None = None,
        apply_primary_beam: builtins.bool | None = None,
        auto_mask: builtins.int | None = None,
        auto_threshold: builtins.float | None = None,
        abs_threshold: builtins.float | None = None,
        avg_freq_res: builtins.float | None = None,
        avg_time_res: builtins.float | None = None,
        channels_out: builtins.int | None = None,
        clean_iterations: builtins.int | None = None,
        clean_threshold: builtins.float | None = None,
        centre: Centre | None = None,
        custom_centre_dec: builtins.float | None = None,
        custom_centre_ra: builtins.float | None = None,
        flag_edge_width: builtins.float | None = None,
        image_size: builtins.int | None = None,
        join_channels: builtins.bool | None = None,
        join_polarizations: builtins.bool | None = None,
        mgain: builtins.float | None = None,
        multiscale: builtins.bool | None = None,
        nmiter: builtins.int | None = None,
        no_apply_amps: builtins.bool | None = None,
        nwlayers: builtins.int | None = None,
        output_mode: OutputMode | None = None,
        pixel_scale: builtins.float | None = None,
        pol: Polarization | None = None,
        robust: builtins.float | None = None,
        uvw_max: builtins.float | None = None,
        uvw_min: builtins.float | None = None,
        weighting: Weighting | None = None,
        wstack_nwlayers: builtins.int | None = None,
        allow_resubmit: builtins.bool | None = None,
    ) -> JobSubmittedResponse:
        r"""
        Submit an imaging job that starts from an obsid.

        Every keyword argument that is `None` uses the MWA ASVO's default.

        Args:
            obs_id: The obsid.
            delivery: Where the MWA ASVO delivers the data.
            delivery_format: How the MWA ASVO packages the files.
            apply_di_cal: Apply the DI calibration solution.
            apply_primary_beam: Apply the primary beam correction.
            auto_mask: The WSClean -auto-mask value.
            auto_threshold: The WSClean -auto-threshold value.
            abs_threshold: The absolute cleaning threshold (Jy).
            avg_freq_res: The frequency resolution to average to before
                imaging (kHz).
            avg_time_res: The time resolution to average to before imaging
                (s).
            channels_out: The number of output channel groups.
            clean_iterations: The WSClean -niter value.
            clean_threshold: The WSClean cleaning threshold (Jy). This
                field is deprecated in the API: use `abs_threshold`.
            centre: Where to centre the image. `Centre.Custom` needs
                `custom_centre_ra` and `custom_centre_dec`.
            custom_centre_dec: The custom phase centre's declination
                (degrees).
            custom_centre_ra: The custom phase centre's right ascension
                (degrees).
            flag_edge_width: The width of the frequency edge flagging (kHz).
            image_size: The WSClean image size in pixels. Only the sizes
                that the MWA ASVO accepts are valid.
            join_channels: Join the output channel groups for cleaning.
            join_polarizations: Join the polarisations for cleaning.
            mgain: The WSClean -mgain value.
            multiscale: Use WSClean multiscale cleaning.
            nmiter: The WSClean -nmiter value. Must be greater than zero.
            no_apply_amps: Do not apply the amplitude calibration solutions.
            nwlayers: The number of w-projection layers. This field is
                deprecated in the API: use `wstack_nwlayers`.
            output_mode: The products to return.
            pixel_scale: The pixel scale (arcsec per pixel).
            pol: The polarisation to image.
            robust: The WSClean -robust value.
            uvw_max: The maximum uv distance to image (wavelengths).
            uvw_min: The minimum uv distance to image (wavelengths).
            weighting: The WSClean weighting scheme.
            wstack_nwlayers: The number of w-stacking layers.
            allow_resubmit: Submit the job even if an identical one has
                completed.

        Returns:
            The server's reply, with the new job's ID.

        Raises:
            ValueError: `obs_id` is not a valid obsid, or an argument is
                outside what the MWA ASVO accepts (for example `mgain`
                above 1, or an `image_size` that is not a supported size).
                The message names the argument and its limits. Nothing is
                sent.
            AsvoApiError: The request failed.
        """
    def submit_image_from_job(
        self,
        obs_id: builtins.int,
        source_job_id: builtins.int,
        *,
        delivery: Delivery | None = None,
        delivery_format: DeliveryFormat | None = None,
        apply_primary_beam: builtins.bool | None = None,
        auto_mask: builtins.int | None = None,
        auto_threshold: builtins.float | None = None,
        abs_threshold: builtins.float | None = None,
        channels_out: builtins.int | None = None,
        clean_iterations: builtins.int | None = None,
        clean_threshold: builtins.float | None = None,
        image_size: builtins.int | None = None,
        join_channels: builtins.bool | None = None,
        join_polarizations: builtins.bool | None = None,
        mgain: builtins.float | None = None,
        multiscale: builtins.bool | None = None,
        nmiter: builtins.int | None = None,
        nwlayers: builtins.int | None = None,
        output_mode: OutputMode | None = None,
        pixel_scale: builtins.float | None = None,
        pol: Polarization | None = None,
        robust: builtins.float | None = None,
        uvw_max: builtins.float | None = None,
        uvw_min: builtins.float | None = None,
        weighting: Weighting | None = None,
        wstack_nwlayers: builtins.int | None = None,
        allow_resubmit: builtins.bool | None = None,
    ) -> JobSubmittedResponse:
        r"""
        Submit an imaging job that starts from an existing conversion job.

        Every keyword argument that is `None` uses the MWA ASVO's default.
        The arguments are those of `submit_imaging_job`, except that the
        data come from a conversion job, so there are no calibration,
        averaging, flagging or phase centre arguments.

        Args:
            obs_id: The obsid.
            source_job_id: The ID of the conversion job to image. Must be
                greater than zero.

        Returns:
            The server's reply, with the new job's ID.

        Raises:
            ValueError: `obs_id` is not a valid obsid, `source_job_id` is
                zero, or an argument is outside what the MWA ASVO accepts
                (see `submit_imaging_job`). Nothing is sent.
            AsvoApiError: The request failed.
        """
    def submit_voltage_job(
        self,
        obs_id: builtins.int,
        offset: builtins.int,
        duration: builtins.int,
        *,
        delivery: builtins.str | None = None,
        from_channel: builtins.int | None = None,
        to_channel: builtins.int | None = None,
        allow_resubmit: builtins.bool | None = None,
    ) -> JobSubmittedResponse:
        r"""
        Submit a job to download an observation's voltage data.

        Every keyword argument that is `None` uses the MWA ASVO's default.

        Args:
            obs_id: The obsid.
            offset: The offset in seconds from the start GPS time of the
                observation, from 0 to 5400.
            duration: The duration to download, in seconds.
            delivery: Where the MWA ASVO delivers the data. The only valid
                value is "scratch", which needs the "mwavcs" Pawsey Group
                on your MWA ASVO profile.
            from_channel: The first receiver channel number (0 to 255).
            to_channel: The last receiver channel number (0 to 255).
            allow_resubmit: Submit the job even if an identical one has
                completed.

        Returns:
            The server's reply, with the new job's ID.

        Raises:
            ValueError: `obs_id` is not a valid obsid, or `offset` is not
                from 0 to 5400. Nothing is sent.
            OverflowError: A channel number is not from 0 to 255.
            AsvoApiError: The request failed.
        """
    def submit_beamformer_job(
        self,
        obs_id: builtins.int,
        *,
        delivery: Delivery | None = None,
        delivery_format: DeliveryFormat | None = None,
        allow_resubmit: builtins.bool | None = None,
    ) -> JobSubmittedResponse:
        r"""
        Submit a job to download an observation's beamformer data.

        The arguments are those of `submit_download_vis_job`.

        Returns:
            The server's reply, with the new job's ID.

        Raises:
            ValueError: `obs_id` is not a valid obsid.
            AsvoApiError: The request failed.
        """
    def cancel_job(self, job_id: builtins.int) -> JobSubmittedResponse:
        r"""
        Cancel a job.

        Args:
            job_id: The ID of the job to cancel.

        Returns:
            The server's reply. Its `job_id` is the job in the request. The
            MWA ASVO answers the cancellation of a job that is already
            cancelled with a normal reply and not an error, so no exception
            is raised. The reason is in `message`. Any other refusal is an
            error.

        Raises:
            OverflowError: `job_id` is negative or too large to be a job ID.
            AsvoApiError: The request failed, for example because there is
                no such job.
        """
    def download_job(
        self,
        job_id: builtins.int,
        download_dir: builtins.str | os.PathLike | pathlib.Path,
        *,
        keep_tar: builtins.bool = False,
        no_resume: builtins.bool = False,
        hash: builtins.bool = True,
        progress: collections.abc.Callable[[DownloadProgress], builtins.object] | None = None,
        buffer_size: builtins.int | None = None,
        retry_duration: builtins.float | None = None,
        download_number: builtins.int = 1,
        download_count: builtins.int = 1,
    ) -> None:
        r"""
        Download the files of a job.

        The job must be ready (see `AsvoJobVec.all_ready`). The call blocks
        until the download ends, with the GIL released. Ctrl-C stops the
        download at the next chunk and raises `KeyboardInterrupt`, when the
        call is made from the main thread. A partial file stays on disk, so
        a new call resumes it (unless `no_resume`).

        Args:
            job_id: The job ID.
            download_dir: The directory for the files. It must exist.
            keep_tar: Keep the tar file as it is. `False` unpacks it into
                `download_dir` while it downloads (then there is no resume).
            no_resume: Download the whole file again, even if part of it is
                on disk.
            hash: Check the SHA-1 hash of the file against the MWA ASVO's.
            progress: A function to call with each `DownloadProgress` event,
                or `None`. `Advanced` events are combined, so the function is
                called about 10 times a second at most. If it raises, the
                download stops and its exception is raised.
            buffer_size: How many bytes to hold in memory before they are
                written. `None` uses the library default (100 MiB).
            retry_duration: How long to retry a failing download, in
                seconds. 0 disables retries. `None` uses the library default
                (900 s).
            download_number: The number of this download, in a series,
                for the progress and log label (`[1/2]`).
            download_count: How many downloads there are in the series.

        Raises:
            AsvoError: The job is missing, not ready or has no files, a
                transfer failed, or the hash does not match.
            AsvoApiError: Getting the job list failed.
            ValueError: `download_dir` or `retry_duration` is not valid.
            KeyboardInterrupt: Ctrl-C was pressed.
        """
    def download_obs(
        self,
        obs_id: builtins.int,
        download_dir: builtins.str | os.PathLike | pathlib.Path,
        *,
        keep_tar: builtins.bool = False,
        no_resume: builtins.bool = False,
        hash: builtins.bool = True,
        progress: collections.abc.Callable[[DownloadProgress], builtins.object] | None = None,
        buffer_size: builtins.int | None = None,
        retry_duration: builtins.float | None = None,
        download_number: builtins.int = 1,
        download_count: builtins.int = 1,
    ) -> None:
        r"""
        Download the files of the one ready job for an obsid.

        The arguments, and the way the download runs, are those of
        `download_job`.

        Args:
            obs_id: The obsid. There must be exactly one ready job for it.

        Raises:
            ValueError: `obs_id` is not a valid obsid.
            AsvoError: No job, no ready job, or more than one ready job has
                this obsid, or the download failed (see `download_job`).
            AsvoApiError: Getting the job list failed.
            KeyboardInterrupt: Ctrl-C was pressed.
        """

class AsvoError(builtins.Exception):
    r"""
    A download or job check failed. `kind` is the Rust `AsvoError` variant.

    `kind` is always set. The other attributes are set only for the kinds shown. A failed API call during a download raises `AsvoApiError`, not this.
    """

    kind: builtins.str
    r"""
    The variant, for example "NoAsvoJob", "JobFailed", "NotReady", "HashMismatch" or "Interrupted".
    """
    job_id: builtins.int
    r"""
    NoAsvoJob, JobFailed, JobExpired, JobCancelled, NotReady, NoFiles, HashMismatch, NoUrl, NoPath and Http404Error.
    """
    obs_id: builtins.int
    r"""
    JobFailed, NoObsId, NoJobReadyForObsId and TooManyObsIds.
    """
    error: builtins.str
    r"""
    JobFailed: the job's error message.
    """
    error_code: builtins.int | None
    r"""
    JobFailed: the job's error code, or None.
    """
    job_state: AsvoJobState
    r"""
    NotReady: the job's state.
    """
    file: builtins.str
    r"""
    HashMismatch.
    """
    calculated_hash: builtins.str
    r"""
    HashMismatch.
    """
    expected_hash: builtins.str
    r"""
    HashMismatch.
    """
    status: builtins.int
    r"""
    HttpError: the HTTP status code.
    """
    message: builtins.str
    r"""
    HttpError.
    """
    str: builtins.str
    r"""
    InvalidJobState and InvalidJobType: the text that could not be parsed.
    """
    name: builtins.str
    r"""
    InvalidEnvironment: the name of the environment variable.
    """
    value: builtins.str
    r"""
    InvalidEnvironment: its value.
    """
    problem: builtins.str
    r"""
    InvalidEnvironment: what is wrong with it.
    """

@typing.final
class AsvoFilesArray:
    r"""
    One file of a job's product.
    """
    @property
    def type(self) -> Delivery:
        r"""
        Where the file is delivered.
        """
    @property
    def url(self) -> builtins.str | None:
        r"""
        The download URL (Acacia delivery), or `None`.
        """
    @property
    def path(self) -> builtins.str | None:
        r"""
        The path on the filesystem (Scratch or DUG delivery), or `None`.
        """
    @property
    def size(self) -> builtins.int:
        r"""
        The size of the file in bytes.
        """
    @property
    def sha1(self) -> builtins.str | None:
        r"""
        The file's SHA-1 hash, or `None`.
        """
    @property
    def format(self) -> builtins.str | None:
        r"""
        The file's format, as the MWA ASVO gives it, or `None`.
        """

@typing.final
class AsvoJob:
    r"""
    An MWA ASVO job.
    """
    @property
    def job_id(self) -> builtins.int:
        r"""
        The job ID.
        """
    @property
    def obs_id(self) -> builtins.int:
        r"""
        The obsid.
        """
    @property
    def job_type(self) -> AsvoJobType:
        r"""
        The job type.
        """
    @property
    def job_state(self) -> AsvoJobState:
        r"""
        The job state.
        """
    @property
    def error_code(self) -> builtins.int | None:
        r"""
        The server's error code, or `None`. The MWA ASVO does not document
        its values, so it is given as it is.
        """
    @property
    def error_text(self) -> builtins.str | None:
        r"""
        The server's error message, or `None`. A job in the `Error` state
        has its message here.
        """
    @property
    def product(self) -> AsvoJobProduct | None:
        r"""
        The job's product (its files), or `None` if the job has none yet.
        """
    @property
    def completed(self) -> datetime.datetime | None:
        r"""
        When the job completed (UTC), or `None`.
        """
    @property
    def created(self) -> datetime.datetime:
        r"""
        When the job was created (UTC).
        """
    @property
    def started(self) -> datetime.datetime | None:
        r"""
        When the job started (UTC), or `None` if it has not started.
        """
    @property
    def modified(self) -> datetime.datetime | None:
        r"""
        When the job was last changed (UTC), or `None`.
        """
    @property
    def user_id(self) -> builtins.int:
        r"""
        The ID of the user who submitted the job.
        """
    @property
    def first_name(self) -> builtins.str:
        r"""
        The first name of the user who submitted the job.
        """
    @property
    def last_name(self) -> builtins.str:
        r"""
        The last name of the user who submitted the job.
        """
    @property
    def job_params(self) -> builtins.dict[builtins.str, typing.Any]:
        r"""
        The job's parameters as the server gives them, as a `dict`.
        """

@typing.final
class AsvoJobProduct:
    r"""
    The product of a completed job: its files.
    """
    @property
    def files(self) -> builtins.list[AsvoFilesArray]:
        r"""
        The job's files.
        """

@typing.final
class AsvoJobVec:
    r"""
    A list of MWA ASVO jobs. Supports `len()`, indexing and iteration.
    """
    def __len__(self) -> builtins.int: ...
    def __getitem__(self, index: builtins.int) -> AsvoJob: ...
    def __iter__(self) -> typing.Iterator[AsvoJob]: ...
    def filter(
        self,
        job_ids: typing.Sequence[builtins.int] | None = None,
        obs_ids: typing.Sequence[builtins.int] | None = None,
        job_types: typing.Sequence[AsvoJobType] | None = None,
        job_states: typing.Sequence[AsvoJobState] | None = None,
    ) -> AsvoJobVec:
        r"""
        Keep only the jobs that match every given filter. A filter that is
        `None` or empty does not filter. States compare by kind only, so
        `AsvoJobState.Error` matches every job with an error.

        Raises:
            ValueError: An obsid is not valid.
        """
    def all_ready(self, job_ids: typing.Sequence[builtins.int]) -> builtins.bool:
        r"""
        Whether all of `job_ids` are ready for download. `False` means some
        are still in progress.

        This makes no request: to wait, call `AsvoClient.get_jobs` and this
        in a loop.

        Raises:
            AsvoError: A job is missing, has an error, has expired or has
                been cancelled.
        """
    def json(self) -> builtins.str:
        r"""
        The jobs as a JSON object keyed by job ID, as `giant-squid list
        --json` prints. The keys are the OpenAPI names (`obs_id`, `job_id`,
        `job_type`, `job_state`, `product`, `created`, `started`,
        `completed`, `modified`, `error_code`, `error_text`, `user_id`, `first_name`,
        `last_name`, `job_params`; and, in `product.files`, `type`, `url`,
        `path`, `size`, `sha1`, `format` for each file).
        """

class DownloadProgress:
    r"""
    A download progress event, given to the `progress` callback of
    `AsvoClient.download_job` and `AsvoClient.download_obs`.

    For each file there are one or more `Started` events, then zero or more
    `Advanced` events, then one `Finished` event. A second `Started` for the
    same file means that the download started again (for example, the
    server did not honour a resume request), so reset the count. Each
    variant is a subclass, so `isinstance` and `match` work.
    """
    @typing.final
    class Started(DownloadProgress):
        r"""
        A file download starts, or starts again.
        """

        __match_args__ = (
            "job_id",
            "label",
            "total_bytes",
            "position",
        )
        @property
        def job_id(self) -> builtins.int:
            r"""
            The MWA ASVO job ID.
            """
        @property
        def label(self) -> builtins.str:
            r"""
            A human-readable label, for example `Job ID 123 (obsid:
            1234567890) [1/2]:`.
            """
        @property
        def total_bytes(self) -> builtins.int:
            r"""
            The size of the file in bytes.
            """
        @property
        def position(self) -> builtins.int:
            r"""
            The bytes already on disk (not zero for a resumed download).
            """
        def __new__(
            cls, job_id: builtins.int, label: builtins.str, total_bytes: builtins.int, position: builtins.int
        ) -> DownloadProgress.Started: ...

    @typing.final
    class Advanced(DownloadProgress):
        r"""
        `bytes` more bytes were written. Events are combined, so there are
        about 10 a second at most.
        """

        __match_args__ = ("bytes",)
        @property
        def bytes(self) -> builtins.int:
            r"""
            The number of bytes written since the last `Advanced` event.
            """
        def __new__(cls, bytes: builtins.int) -> DownloadProgress.Advanced: ...

    @typing.final
    class Finished(DownloadProgress):
        r"""
        The file download is complete, or was skipped because the file is
        already on disk.
        """

        __match_args__ = ()
        def __new__(cls) -> DownloadProgress.Finished: ...

@typing.final
class DownloadSettings:
    r"""
    The download settings that the `giant-squid` command reads from the
    environment, to pass to `AsvoClient.download_job` and `download_obs`.
    """
    @property
    def buffer_size(self) -> builtins.int:
        r"""
        How many bytes to hold in memory before they are written. Pass it as
        `buffer_size`.
        """
    @property
    def retry_duration(self) -> builtins.float:
        r"""
        How long to retry a failing download, in seconds. Pass it as
        `retry_duration`.
        """
    @staticmethod
    def from_env() -> DownloadSettings:
        r"""
        Read the settings from the environment.

        `GIANT_SQUID_BUF_SIZE` is a whole number of MiB. `GIANT_SQUID_DOWNLOAD_RETRY_SECS`
        is a whole number of seconds; a value that is not one is logged as a
        warning and the default is used. A setting that is not set has the
        library's default.

        Raises:
            AsvoError: `GIANT_SQUID_BUF_SIZE` is set but is not a whole
                number of MiB, or is too large (kind `InvalidEnvironment`).
        """

@typing.final
class JobSubmittedResponse:
    r"""
    The MWA ASVO's reply to a job submission or to a cancellation.
    """
    @property
    def job_id(self) -> builtins.int:
        r"""
        The ID of the job that was submitted (or cancelled).
        """
    @property
    def message(self) -> builtins.str:
        r"""
        The server's message.
        """
    @property
    def status(self) -> builtins.str:
        r"""
        The server's status text for the request, "success" or "failed". It
        describes the reply, like `message`; it is for display only. Success
        or failure of a call is decided by the HTTP status, so a call that
        fails raises `AsvoApiError`, and this text is not to be used to
        decide whether a call worked.
        """

@typing.final
class AsvoJobState(enum.Enum):
    r"""
    The state of an MWA ASVO job. For `Error`, the message is in
    `AsvoJob.error_text`.
    """

    Queued = ...
    WaitCal = ...
    Staging = ...
    Staged = ...
    Preparing = ...
    Downloading = ...
    Preprocessing = ...
    Imaging = ...
    Delivering = ...
    Ready = ...
    Error = ...
    Expired = ...
    Cancelled = ...

@typing.final
class AsvoJobType(enum.Enum):
    r"""
    The type of an MWA ASVO job.
    """

    Conversion = ...
    DownloadVisibilities = ...
    DownloadMetadata = ...
    DownloadVoltage = ...
    CancelJob = ...
    DownloadBeamformer = ...
    Imaging = ...
    Unknown = ...

@typing.final
class Centre(enum.Enum):
    r"""
    Where to put the phase centre of a conversion job or an imaging job.
    `str()` is the API value.
    """

    Phase = ...
    Pointing = ...
    Custom = ...

@typing.final
class Delivery(enum.Enum):
    r"""
    Where the MWA ASVO delivers a job's files.
    """

    Acacia = ...
    Dug = ...
    Scratch = ...

@typing.final
class DeliveryFormat(enum.Enum):
    r"""
    How the MWA ASVO packages a job's files: one tar file, or separate
    files. `str()` is the API value.
    """

    Tar = ...
    Files = ...

@typing.final
class Output(enum.Enum):
    r"""
    The format of a conversion job's output. `str()` is the API value.
    """

    Ms = ...
    Uvfits = ...

@typing.final
class OutputMode(enum.Enum):
    r"""
    The products an imaging job returns. `str()` is the API value.
    """

    Fits = ...
    AllFits = ...
    AllFiles = ...

@typing.final
class Polarization(enum.Enum):
    r"""
    The polarisation an imaging job images. `str()` is the API value.
    """

    Xx = ...
    Yy = ...
    Xxyy = ...

@typing.final
class Weighting(enum.Enum):
    r"""
    The WSClean weighting scheme of an imaging job. `str()` is the API
    value.
    """

    Briggs = ...
    Uniform = ...
    Natural = ...

def beamformer_job_params(
    obs_id: builtins.int,
    *,
    delivery: Delivery | None = None,
    delivery_format: DeliveryFormat | None = None,
    allow_resubmit: builtins.bool | None = None,
) -> builtins.dict[builtins.str, typing.Any]:
    r"""
    The request body that `AsvoClient.submit_beamformer_job` sends, as a
    `dict`. Makes no request.

    The arguments, the defaults and the argument errors (`ValueError`,
    `OverflowError`) are those of the method.
    """

def conversion_job_params(
    obs_id: builtins.int,
    *,
    delivery: Delivery | None = None,
    delivery_format: DeliveryFormat | None = None,
    output: Output | None = None,
    avg_freq_res: builtins.float | None = None,
    avg_time_res: builtins.float | None = None,
    flag_edge_width: builtins.float | None = None,
    apply_di_cal: builtins.bool | None = None,
    centre: Centre | None = None,
    custom_centre_ra: builtins.float | None = None,
    custom_centre_dec: builtins.float | None = None,
    no_apply_amps: builtins.bool | None = None,
    no_digital_gains: builtins.bool | None = None,
    no_flag_dc: builtins.bool | None = None,
    no_geometry_delay: builtins.bool | None = None,
    no_passband_gains: builtins.bool | None = None,
    no_cable_delay: builtins.bool | None = None,
    no_rfi: builtins.bool | None = None,
    allow_resubmit: builtins.bool | None = None,
) -> builtins.dict[builtins.str, typing.Any]:
    r"""
    The request body that `AsvoClient.submit_conversion_job` sends, as a
    `dict`. Makes no request.

    The arguments, the defaults and the argument errors (`ValueError`,
    `OverflowError`) are those of the method.
    """

def download_meta_job_params(
    obs_id: builtins.int,
    *,
    delivery: Delivery | None = None,
    delivery_format: DeliveryFormat | None = None,
    allow_resubmit: builtins.bool | None = None,
) -> builtins.dict[builtins.str, typing.Any]:
    r"""
    The request body that `AsvoClient.submit_download_meta_job` sends, as a
    `dict`. Makes no request.

    The arguments, the defaults and the argument errors (`ValueError`,
    `OverflowError`) are those of the method.
    """

def download_vis_job_params(
    obs_id: builtins.int,
    *,
    delivery: Delivery | None = None,
    delivery_format: DeliveryFormat | None = None,
    allow_resubmit: builtins.bool | None = None,
) -> builtins.dict[builtins.str, typing.Any]:
    r"""
    The request body that `AsvoClient.submit_download_vis_job` sends, as a
    `dict`. Makes no request.

    The arguments, the defaults and the argument errors (`ValueError`,
    `OverflowError`) are those of the method.
    """

def image_from_job_params(
    obs_id: builtins.int,
    source_job_id: builtins.int,
    *,
    delivery: Delivery | None = None,
    delivery_format: DeliveryFormat | None = None,
    apply_primary_beam: builtins.bool | None = None,
    auto_mask: builtins.int | None = None,
    auto_threshold: builtins.float | None = None,
    abs_threshold: builtins.float | None = None,
    channels_out: builtins.int | None = None,
    clean_iterations: builtins.int | None = None,
    clean_threshold: builtins.float | None = None,
    image_size: builtins.int | None = None,
    join_channels: builtins.bool | None = None,
    join_polarizations: builtins.bool | None = None,
    mgain: builtins.float | None = None,
    multiscale: builtins.bool | None = None,
    nmiter: builtins.int | None = None,
    nwlayers: builtins.int | None = None,
    output_mode: OutputMode | None = None,
    pixel_scale: builtins.float | None = None,
    pol: Polarization | None = None,
    robust: builtins.float | None = None,
    uvw_max: builtins.float | None = None,
    uvw_min: builtins.float | None = None,
    weighting: Weighting | None = None,
    wstack_nwlayers: builtins.int | None = None,
    allow_resubmit: builtins.bool | None = None,
) -> builtins.dict[builtins.str, typing.Any]:
    r"""
    The request body that `AsvoClient.submit_image_from_job` sends, as a
    `dict`. Makes no request.

    The arguments, the defaults and the argument errors (`ValueError`,
    `OverflowError`) are those of the method.
    """

def imaging_job_params(
    obs_id: builtins.int,
    *,
    delivery: Delivery | None = None,
    delivery_format: DeliveryFormat | None = None,
    apply_di_cal: builtins.bool | None = None,
    apply_primary_beam: builtins.bool | None = None,
    auto_mask: builtins.int | None = None,
    auto_threshold: builtins.float | None = None,
    abs_threshold: builtins.float | None = None,
    avg_freq_res: builtins.float | None = None,
    avg_time_res: builtins.float | None = None,
    channels_out: builtins.int | None = None,
    clean_iterations: builtins.int | None = None,
    clean_threshold: builtins.float | None = None,
    centre: Centre | None = None,
    custom_centre_dec: builtins.float | None = None,
    custom_centre_ra: builtins.float | None = None,
    flag_edge_width: builtins.float | None = None,
    image_size: builtins.int | None = None,
    join_channels: builtins.bool | None = None,
    join_polarizations: builtins.bool | None = None,
    mgain: builtins.float | None = None,
    multiscale: builtins.bool | None = None,
    nmiter: builtins.int | None = None,
    no_apply_amps: builtins.bool | None = None,
    nwlayers: builtins.int | None = None,
    output_mode: OutputMode | None = None,
    pixel_scale: builtins.float | None = None,
    pol: Polarization | None = None,
    robust: builtins.float | None = None,
    uvw_max: builtins.float | None = None,
    uvw_min: builtins.float | None = None,
    weighting: Weighting | None = None,
    wstack_nwlayers: builtins.int | None = None,
    allow_resubmit: builtins.bool | None = None,
) -> builtins.dict[builtins.str, typing.Any]:
    r"""
    The request body that `AsvoClient.submit_imaging_job` sends, as a
    `dict`. Makes no request.

    The arguments, the defaults and the argument errors (`ValueError`,
    `OverflowError`) are those of the method.
    """

def parse_many_job_ids_or_obs_ids(
    strings: typing.Sequence[builtins.str],
) -> tuple[builtins.list[builtins.int], builtins.list[builtins.int]]:
    r"""
    Sort job IDs and obsids, as the CLI does with its arguments.

    A string that is an integer is an obsid if it is a valid obsid, and a job
    ID if not. Any other string is the path of a file of job IDs and obsids,
    separated by whitespace.

    Args:
        strings: The job IDs, obsids and file paths.

    Returns:
        The job IDs and the obsids, each in the order given.

    Raises:
        ValueError: Text in a file is not an integer.
        OSError: A file cannot be read (for example `FileNotFoundError`).
    """

def reset_logging() -> None:
    r"""
    Make Python see changes to its logging configuration.

    For speed, the module caches each Python logger and its level the
    first time a Rust log record uses it. Call this after you change
    the logging configuration (for example, after `logging.basicConfig`
    or `setLevel`), if the module has already logged.
    """

def voltage_job_params(
    obs_id: builtins.int,
    offset: builtins.int,
    duration: builtins.int,
    *,
    delivery: builtins.str | None = None,
    from_channel: builtins.int | None = None,
    to_channel: builtins.int | None = None,
    allow_resubmit: builtins.bool | None = None,
) -> builtins.dict[builtins.str, typing.Any]:
    r"""
    The request body that `AsvoClient.submit_voltage_job` sends, as a
    `dict`. Makes no request.

    The arguments, the defaults and the argument errors (`ValueError`,
    `OverflowError`) are those of the method.
    """
