#!/usr/bin/env python3
"""Make an importable copy of the stub, for pdoc (see tools/generate_python_docs.sh).

pdoc documents the stub, mwa_giant_squid.pyi, and not the built module: the stub is the public API that stubtest
checks against the module, and it has the types and the docstrings. pdoc cannot use the built module directly:

- PyO3 builds the properties of a class from a randomly seeded HashMap, so the order of the members changes from one
  import to the next, and so would the pages.
- A PyO3 complex enum (`DownloadProgress`) has its variants as nested subclasses, so `DownloadProgress.Started.Started`
  is `DownloadProgress.Started`. pdoc's stub support recurses into it without end.

A stub is not made to be executed, so this script writes a copy that executes, and changes only what must change:

- `from __future__ import annotations`, for the forward references (`-> AsvoClient` in `class AsvoClient`).
- A nested class does not name its enclosing class as a base (`class Started(DownloadProgress)` cannot execute in the
  body of `DownloadProgress`).
- The members of an enum, which are `...` in the stub, get their API value from the built module. With `...`, every
  member would be an alias of the first one.

Usage:
    uv run python tools/generate_python_docs.py <stub> <output .py file>
"""

from __future__ import annotations

import argparse
import ast
import enum
import sys
from pathlib import Path

import mwa_giant_squid

# The enums whose value is the API's code (an int). The value of every other enum is its `str()`, the API value.
INT_VALUED_ENUMS = frozenset({"JobType"})

# The help of the script.
DESCRIPTION = "Make an importable copy of the stub, for pdoc."

# The comment at the top of the generated file.
GENERATED_HEADER = "# Generated by tools/generate_python_docs.py from mwa_giant_squid.pyi, for pdoc. Do not edit.\n"


def is_enum_class(node: ast.ClassDef) -> bool:
    """Whether a class of the stub is an enum.

    Args:
        node: The class.

    Returns:
        True if one of its bases is `enum.Enum`.
    """
    return any(
        isinstance(base, ast.Attribute)
        and base.attr == enum.Enum.__name__
        and isinstance(base.value, ast.Name)
        and base.value.id == enum.__name__
        for base in node.bases
    )


def enum_value(class_name: str, member: str) -> int | str:
    """The API value of an enum member, from the built module.

    Args:
        class_name: The name of the enum.
        member: The name of the member.

    Returns:
        The API code for an enum in `INT_VALUED_ENUMS`, otherwise the `str()` of the member.

    Raises:
        AttributeError: The built module does not have the enum or the member, so it does not match the stub.
    """
    value = getattr(getattr(mwa_giant_squid, class_name), member)
    if class_name in INT_VALUED_ENUMS:
        return int(value)
    return str(value)


class StubToModule(ast.NodeTransformer):
    """Make the classes of the stub executable (see the module docstring)."""

    def __init__(self) -> None:
        """Start outside of any class."""
        self.enclosing: list[str] = []

    def visit_ClassDef(self, node: ast.ClassDef) -> ast.ClassDef:
        """Change one class, then its nested classes.

        Args:
            node: The class.

        Returns:
            The changed class.
        """
        if self.enclosing:
            outer = self.enclosing[-1]
            node.bases = [base for base in node.bases if not (isinstance(base, ast.Name) and base.id == outer)]
        if is_enum_class(node):
            for statement in node.body:
                if (
                    isinstance(statement, ast.Assign)
                    and len(statement.targets) == 1
                    and isinstance(statement.targets[0], ast.Name)
                    and isinstance(statement.value, ast.Constant)
                    and statement.value.value is Ellipsis
                ):
                    statement.value = ast.Constant(enum_value(node.name, statement.targets[0].id))
        self.enclosing.append(node.name)
        self.generic_visit(node)
        self.enclosing.pop()
        return node


def has_docstring(module: ast.Module) -> bool:
    """Whether a module starts with a docstring.

    Args:
        module: The module.

    Returns:
        True if the first statement is a string.
    """
    return bool(
        module.body
        and isinstance(module.body[0], ast.Expr)
        and isinstance(module.body[0].value, ast.Constant)
        and isinstance(module.body[0].value.value, str)
    )


def stub_to_module(stub: str) -> str:
    """Make an importable module of the stub.

    Args:
        stub: The text of the stub.

    Returns:
        The text of the module.
    """
    tree = StubToModule().visit(ast.parse(stub))
    future = ast.ImportFrom(module="__future__", names=[ast.alias(name="annotations")], level=0)
    # After the module docstring, so that it stays the docstring.
    tree.body.insert(1 if has_docstring(tree) else 0, future)
    return GENERATED_HEADER + ast.unparse(ast.fix_missing_locations(tree)) + "\n"


def main() -> int:
    """Write the importable copy of the stub.

    Returns:
        The exit code.
    """
    parser = argparse.ArgumentParser(description=DESCRIPTION)
    parser.add_argument("stub", type=Path, help="the stub, mwa_giant_squid.pyi")
    parser.add_argument("output", type=Path, help="the .py file to write")
    args = parser.parse_args()
    args.output.write_text(stub_to_module(args.stub.read_text()))
    return 0


if __name__ == "__main__":
    sys.exit(main())
