#!/usr/bin/env bash

# Fail the script on any error
set -euo pipefail

#
# Regenerates src/asvo/apiv2/openapi.rs from the MWA ASVO v2 OpenAPI schema,
# using typify (https://github.com/oxidecomputer/typify) to turn the schema
# definitions into Rust types.
#
# It assumes:
# 1. You run this from inside the "tools" directory
# 2. You have `cargo-typify` installed (cargo install cargo-typify)
# 3. You have `curl` and `python3` available
#
# The OpenAPI URL can be overridden for testing, e.g.:
#   OPENAPI_URL=http://localhost:8000/openapi.json ./generate_openapi.sh
#

OPENAPI_URL="${OPENAPI_URL:-https://dev-asvo.mwatelescope.org/openapi.json}"
OUTPUT_FILE="src/asvo/apiv2/openapi.rs"

# --- Preflight checks (before we go anywhere, so there's nothing to unwind) -

if ! command -v cargo-typify &> /dev/null; then
    echo "Error: cargo-typify is not installed." >&2
    echo "Install it with: cargo install cargo-typify" >&2
    exit 1
fi

if ! command -v curl &> /dev/null; then
    echo "Error: curl is required but was not found on PATH." >&2
    exit 1
fi

if ! command -v python3 &> /dev/null; then
    echo "Error: python3 is required but was not found on PATH." >&2
    exit 1
fi

# Switch to the root giant-squid dir
pushd .. > /dev/null

RAW_OPENAPI="$(mktemp --suffix=.json)"
SCHEMAS_FOR_TYPIFY="$(mktemp --suffix=.json)"
FINAL_TMP="$(mktemp --suffix=.rs)"
cleanup() {
    rm -f "$RAW_OPENAPI" "$SCHEMAS_FOR_TYPIFY" "$FINAL_TMP"
    popd > /dev/null
}
trap cleanup EXIT

# --- Download ----------------------------------------------------------

echo "Downloading OpenAPI schema from ${OPENAPI_URL}..."
curl -fsS "$OPENAPI_URL" -o "$RAW_OPENAPI"

if ! python3 -c "import json; json.load(open(\"$RAW_OPENAPI\"))" 2>/dev/null; then
    echo "Error: downloaded content from ${OPENAPI_URL} is not valid JSON." >&2
    exit 1
fi

# --- Convert for typify --------------------------------------------------
#
# typify reads plain JSON Schema documents (a "definitions" map of named
# schemas), not full OpenAPI documents. Extract components.schemas into its
# own document and rewrite $ref pointers to match.

echo "Converting schema for typify..."
python3 - "$RAW_OPENAPI" "$SCHEMAS_FOR_TYPIFY" <<'PYEOF'
import json
import sys

in_path, out_path = sys.argv[1], sys.argv[2]

with open(in_path) as f:
    doc = json.load(f)

schemas = doc.get("components", {}).get("schemas")
if not schemas:
    sys.exit("Error: no components.schemas found in the downloaded OpenAPI document.")


def rewrite_refs(node):
    if isinstance(node, dict):
        for k, v in node.items():
            if k == "$ref" and isinstance(v, str) and v.startswith("#/components/schemas/"):
                node[k] = v.replace("#/components/schemas/", "#/definitions/")
            else:
                rewrite_refs(v)
    elif isinstance(node, list):
        for v in node:
            rewrite_refs(v)


rewrite_refs(schemas)

out = {
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": schemas,
}

with open(out_path, "w") as f:
    json.dump(out, f, indent=2)
PYEOF

# --- Generate Rust types with typify ------------------------------------

echo "Running typify..."
mkdir -p "$(dirname "$OUTPUT_FILE")"
cargo typify "$SCHEMAS_FOR_TYPIFY" --output "$OUTPUT_FILE"

# --- Prepend the autogenerated-file header ------------------------------

echo "Adding autogenerated-file header..."
cat > "$FINAL_TMP" <<'HEADER'
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

//
// The code in this file is AUTOGENERATED by tools/generate_openapi.sh
// Manual edits or modifications will be lost next time it is generated!
//
HEADER
cat "$OUTPUT_FILE" >> "$FINAL_TMP"
mv "$FINAL_TMP" "$OUTPUT_FILE"

echo "Done: ${OUTPUT_FILE}"

