on:
  push:
    tags-ignore:
      - "**"
    branches:
      - "**"
  pull_request:

env:
  MWA_ASVO_API_KEY: ${{ secrets.MWA_ASVO_API_KEY }}

name: Generate Coverage report

jobs:
  coverage:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust, stable minimal toolchain
        uses: dtolnay/rust-toolchain@v1
        with:          
          toolchain: stable
          components: llvm-tools
      
      - name: Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov

      - name: Generate test lcov coverage into coverage/ dir
        run: |
          mkdir -p coverage
          cargo llvm-cov clean --workspace
          cargo llvm-cov --all --lcov --output-path coverage/coverage.lcov
          # this uses the result of the previous run to generate a text summary
          cargo llvm-cov report
      - name: Upload reports to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
