---
name: Release

# Do this on every push
on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux-release:
    name: Build release for Linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Rust, stable minimal toolchain
      uses: dtolnay/rust-toolchain@v1
      with:          
        toolchain: stable

    - name: Build
      run: .github/workflows/build.sh

    - name: Upload tarball
      uses: actions/upload-artifact@v2
      with:
        name: linux.tar.gz
        path: "*.tar.gz"
        if-no-files-found: error

  build-macos-13-release:
    name: Build release for MacOS x86_64
    runs-on: macos-13

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Rust, stable minimal toolchain
      uses: dtolnay/rust-toolchain@v1
      with:          
        toolchain: stable

    - name: Build
      run: .github/workflows/build.sh

    - name: Upload tarball
      uses: actions/upload-artifact@v4
      with:
        name: macos13.tar.gz
        path: "*.tar.gz"
        if-no-files-found: error

  build-macos-14-release:
    name: Build release for MacOS arm64
    runs-on: macos-14

    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Rust, stable minimal toolchain
      uses: dtolnay/rust-toolchain@v1
      with:          
        toolchain: stable

    - name: Build
      run: .github/workflows/build.sh

    - name: Upload tarball
      uses: actions/upload-artifact@v4
      with:
        name: macos14.tar.gz
        path: "*.tar.gz"
        if-no-files-found: error

  create-release:
    name: Create a new release
    runs-on: ubuntu-latest
    needs: [build-linux-release, build-macos-13-release, build-macos-14-release]
    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: linux.tar.gz

      - name: Download MacOS 13 x86_64 artifact
        uses: actions/download-artifact@v4
        with:
          name: macos13.tar.gz

      - name: Download MacOS 14 arm64 artifact
        uses: actions/download-artifact@v4
        with:
          name: macos14.tar.gz

      - name: Provide new release asset
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            *.tar.gz
