---
name: Cross-platform tests

# Do this on every push, except tags

on:
  push:
    tags-ignore:
      - "**"
    branches:
      - "**"
  pull_request:

env:
  CARGO_TERM_COLOR: always
  MWA_ASVO_API_KEY: ${{ secrets.MWA_ASVO_API_KEY }}

jobs:
  test:
    name: Test ${{ matrix.os }} toolchain ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04-arm, macOS-13, macOS-14]
        toolchain: [stable]
        include:
          - os: ubuntu-latest
            toolchain: "msrv"
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get MSRV
      if: matrix.toolchain == 'msrv'
      run:
        echo "MSRV=$(grep -m1 'rust-version' Cargo.toml | sed 's|.*\"\(.*\)\"|\1|')" >> "$GITHUB_ENV"

    - name: Install Rust minimal toolchain ${{ matrix.toolchain }}
      uses: dtolnay/rust-toolchain@v1
      with:          
        toolchain: ${{ matrix.toolchain == 'msrv' && env.MSRV || matrix.toolchain }}        
    
    - name: Run tests
      run: cargo test --locked
